Add label new
jabardigitalservice/pikobar-flutter pull request #493
Opened 2020-12-29 02:03 UTC by gaganugraha33

- menambahkan label baru di menu informasi covid
- membuat base function untuk label baru

[[S15 App] Penambahan label BARU berwarna merah di setiap data di Info Praktikal/Berita Terkini/Video Terkini/Dokumen](https://trello.com/c/IALTxjYW)

2020-12-29 02:11 UTC, gaganugraha33 commented
review gan @anandarh @jaluowen @aldiiii

2020-12-29 05:23 UTC, anandarh requested changes

2020-12-29 05:23 UTC, anandarh commented on lib/screens/home/components/Documents.dart
> +                                                    )
Gan @gaganugraha33, ini ada looping di beberapa screen, sepertinya bisa dijadikan satu komponen baru, jadi bisa dipanggil dari sceen lain juga.

2020-12-29 05:23 UTC, anandarh commented on lib/screens/home/components/InfoGraphics.dart
> +                                                    )
Yang ini sama gan

2020-12-29 05:23 UTC, anandarh commented on lib/screens/home/components/NewsScreeen.dart
> +                                                      )
Ini juga gan

2020-12-29 05:23 UTC, anandarh commented on lib/screens/home/components/VideoList.dart
> +                                        )
Ini juga gan 😄

2020-12-29 06:16 UTC, gaganugraha33 commented on lib/screens/home/components/Documents.dart
> +                                                    )
siap gan udah dibikin komponen sekarang 😄 @anandarh

2020-12-29 08:35 UTC, anandarh approved these changes

2020-12-29 12:04 UTC, aldiiii approved these changes

2020-12-29 12:08 UTC, aldiiii reviewed
conflict

2020-12-31 11:27 UTC, jaluowen approved these changes

2020-12-31 11:27 UTC, merged