Add notif tab
jabardigitalservice/pikobar-flutter pull request #501
Opened 2021-01-12 02:49 UTC by gaganugraha33

- menambahkan bulatan merah pada tab informasi covid
- menambahkan label baru di menu list berita, infro praktikal, video & dokumen
- menyesuaikan base widget CustomBubbletab untuk label baru

[[S15 App] Penambahan bulatan Merah pada tab Informasi Covid-19](https://trello.com/c/Qz8QZyTj)

2021-01-12 03:01 UTC, gaganugraha33 commented
review gan @anandarh @jaluowen @aldiiii

2021-01-12 08:03 UTC, jaluowen commented
conflicts mang @gaganugraha33

2021-01-12 08:15 UTC, gaganugraha33 commented
sipp, udah di fix mang @jaluowen

2021-01-12 10:46 UTC, anandarh requested changes

2021-01-12 10:46 UTC, anandarh commented on lib/screens/home/components/ImportantInfoScreen.dart
>                  )
Gan @gaganugraha33, bloc ini sepertinya udah ga kepake kalau return widgetnya dijadikan comment. Atau gimana itu?

2021-01-13 02:49 UTC, gaganugraha33 commented on lib/screens/home/components/ImportantInfoScreen.dart
>                  )
oiya, ini screennya udah ga dipake gan, sekalian udah dihapus tadi @anandarh

2021-01-13 03:45 UTC, anandarh commented on lib/screens/home/components/ImportantInfoScreen.dart
>                  )
Oke sip gan.

2021-01-14 03:30 UTC, jaluowen approved these changes

2021-01-14 03:30 UTC, merged