[Improve] Disable Save Button
jabardigitalservice/pikobar-flutter pull request #515
Opened 2021-01-25 09:36 UTC by jaluowen

- Disable tombol Simpan di Lapor Kesehatan Harian jika kolom mandatory belum terisi

[[S16 App] Disable tombol Simpan di Lapor Kesehatan Harian jika kolom mandatory belum terisi](https://trello.com/c/joewjaW4/382-s16-app-disable-tombol-simpan-di-lapor-kesehatan-harian-jika-kolom-mandatory-belum-terisi)

2021-01-25 09:37 UTC, jaluowen commented
Review kang @aldiiii @gaganugraha33 @anandarh

2021-01-25 09:59 UTC, gaganugraha33 approved these changes

2021-01-26 03:57 UTC, anandarh requested changes

2021-01-26 03:57 UTC, anandarh commented on lib/screens/selfReport/SelfReportFormScreen.dart
> +                        } else if (_bodyTempController.text.isEmpty) {
Yg ini mungkin bisa diperbaiki, supaya tidak ada `empty body` pada statement if
```
if (!isEmptyField()) {
    _saveSelfReport();
} else if (_bodyTempController.text.isEmpty) {
   // Bottom sheet temperature message
       ...
       ...
}  
```

2021-01-26 03:57 UTC, anandarh commented on lib/screens/selfReport/SelfReportFormScreen.dart
> +      }
Ini juga bisa perbaiki jadi 
```
return _checkedItemList.isEmpty 
          || _dateController.text.isEmpty 
          || _quarantineDateController.text.isEmpty;
```

2021-01-26 03:57 UTC, anandarh commented on lib/screens/selfReport/SelfReportFormScreen.dart
> +      }
Ini juga sama yes
```
return _checkedItemList.isEmpty;
```

2021-01-26 04:21 UTC, jaluowen commented on lib/screens/selfReport/SelfReportFormScreen.dart
> +                        } else if (_bodyTempController.text.isEmpty) {
Done mas bram @anandarh

2021-01-26 04:21 UTC, jaluowen commented on lib/screens/selfReport/SelfReportFormScreen.dart
> +      }
Done mas bram @anandarh

2021-01-26 04:21 UTC, jaluowen commented on lib/screens/selfReport/SelfReportFormScreen.dart
> +      }
Done mas bram @anandarh

2021-01-26 08:41 UTC, anandarh approved these changes

2021-01-26 08:42 UTC, merged