Fix Bloc Pre Release
jabardigitalservice/pikobar-flutter pull request #535
Opened 2021-02-02 04:20 UTC by jaluowen

2021-02-02 05:02 UTC, gaganugraha33 approved these changes

2021-02-03 17:52 UTC, anandarh requested changes

2021-02-03 17:52 UTC, anandarh commented on lib/screens/myAccount/ProfileScreen.dart
> +                            _getProfile.profile, _profileLoaded);
Ini langsung tembak jadi `state.profile` aja gan, ga usah di buat variable baru karena hanya dipakai 1x untuk nge-assign.

2021-02-03 17:52 UTC, anandarh commented on lib/screens/selfReport/SelfReportScreen.dart
> +                    ProfileLoaded _getProfile = state;
Ini juga yes

2021-02-04 01:42 UTC, jaluowen commented
mas bram @anandarh ini kan merge ke branch pre-release berarti di close aja kalo gitu ya?

2021-02-05 00:46 UTC, merged