Add Disable Button
jabardigitalservice/pikobar-flutter pull request #537
Opened 2021-02-02 13:31 UTC by jaluowen

- Membuat tombol menjadi disable ketika ada field mandatory yg belum terisi
- Memperbaiki issue minor di sonarqube

[[S16 App] Edit Profil - Disable Button Submit ketika Field Mandatory belum terisi semua](https://trello.com/c/xeRrzd4n/392-s16-app-edit-profil-disable-button-submit-ketika-field-mandatory-belum-terisi-semua)

2021-02-02 13:32 UTC, jaluowen commented
Review mang @aldiiii @anandarh @gaganugraha33

2021-02-03 01:44 UTC, gaganugraha33 approved these changes

2021-02-03 17:38 UTC, anandarh requested changes

2021-02-03 17:38 UTC, anandarh commented on lib/screens/myAccount/EditScreen.dart
> +        bool isConnected = await Connection().checkConnection(kUrlGoogle);
Ini juga yes. Nanti coba kita bahas bareng2 saat weekly. 😉

2021-02-03 17:38 UTC, anandarh commented on lib/screens/myAccount/EditScreen.dart
> +                                        .get();
Kita coba terapkan _best practice_ dalam penulisan kodenya yes, minimal kita coba mulai fokuskan dulu dari pendeklarasian tipe variable.

Ini `var`-nya bisa diganti jadi `final` jika _variable_-nya tidak di-reassign lagi.

2021-02-04 01:51 UTC, jaluowen commented on lib/screens/myAccount/EditScreen.dart
> +                                        .get();
siaap mas bram, sudah disesuaikan :sweat_smile:

2021-02-04 17:47 UTC, anandarh approved these changes

2021-02-04 17:48 UTC, merged