Add Check Distribution Other
jabardigitalservice/pikobar-flutter pull request #646
Opened 2021-05-28 07:24 UTC by jaluowen

- Mengubah halaman cek lokasi lain menggunakan drop down

[[S20 App] Improvement Cek Lokasi Lain menggunakan drop down/search untuk memilih kab/kota dan kecamatan](https://trello.com/c/V5L5cpCz/840-s20-app-improvement-cek-lokasi-lain-menggunakan-drop-down-search-untuk-memilih-kab-kota-dan-kecamatan)

2021-05-31 04:36 UTC, anandarh requested changes

2021-05-31 04:36 UTC, anandarh commented on lib/blocs/area/cityListBloc/CityListBloc.dart
> +  StreamSubscription _subscription;
Specify type annotations. @jaluowen 
`StreamSubscription <Object> _subscription;`

2021-05-31 04:36 UTC, anandarh commented on lib/blocs/area/cityListBloc/CityListEvent.dart
> +  const CityListEvent([List props = const <dynamic>[]]);
Avoid defining unused parameters in constructors.
`[List props = const <dynamic>[]]` hapus aja, tambahin override props di body class abstract-nya. Jadi gini:
```
abstract class CityListEvent extends Equatable {
   const CityListEvent();
   
   @override
   List<Object> get props => <Object>[];
}
```

Supaya nanti kelas2 turunanannya yang ga punya variabel ga perlu implementasi override props lagi.

2021-05-31 04:36 UTC, anandarh commented on lib/blocs/area/cityListBloc/CityListEvent.dart
> +}
Ini bisa dibuat simple, jadi:
`class CityListLoad extends CityListEvent {}`

`toString()` itu akan otomatis di-generate sebenarnya, jadi ga perlu di override. Ini kita cicil beresin dikit2, bersih2 yes. 😄

2021-05-31 04:36 UTC, anandarh commented on lib/blocs/area/cityListBloc/CityListState.dart
> +}
Ini juga sama yes

2021-05-31 04:36 UTC, anandarh commented on lib/blocs/area/cityListBloc/CityListEvent.dart
> +  List<Object> get props => [cityList];
Specify type annotations.
Tambahkan `<Object>`,

```
@override
List<Object> get props => <Object>[cityList];
```

2021-05-31 04:58 UTC, jaluowen commented
Siaap done semua mas bram @anandarh

2021-06-02 02:57 UTC, anandarh approved these changes

2021-06-02 02:59 UTC, anandarh approved these changes

2021-06-03 02:11 UTC, jaluowen commented
review mang @gaganugraha33

2021-06-03 02:22 UTC, gaganugraha33 approved these changes

2021-06-03 02:22 UTC, merged